server:
  port: 8082
spring:
  profiles:
    active: dev
    include: database-dev

  thymeleaf:
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 开启模板缓存（默认值： true ）
    cache: false
    # 检查模板是否存在，然后再呈现
    check-template: false
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: false
    # Content-Type 的值（默认值： text/html ）
    servlet:
      content-type: text/html
    # 模板编码
    encoding: UTF-8
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML)
    mode: HTML
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html
  messages:
    basename: i18n/message
    encoding: UTF-8

mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-value: '1'
      logic-not-delete-value: '0'
      logic-delete-field: is_del
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


async:
  coreSize: 10
  maxSize: 100

userAuth:
  tokenDuration: 3600
